name: rl-imit
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - numpy
  - pandas
  - matplotlib
  - scikit-learn
  - seaborn
  - xgboost
  - pytorch
  - torchvision
  - ipykernel
  - jupyter_client
  - jupyter_core
  - matplotlib-inline
  - pillow
  - pip
  - pip:
      - gym==0.26.2
      - cloudpickle==3.1.0
      - contourpy==1.1.1
      - cycler==0.12.1
      - fonttools==4.54.1
      - importlib-resources==6.4.5
      - joblib==1.4.2
      - kiwisolver==1.4.7
      - pyparsing==3.1.4
      - pytz==2024.2
      - scipy==1.10.1
      - threadpoolctl==3.5.0
      - tzdata==2024.2
